### ISSUE TITLE
Need some help if is posible

### ISSUE THREAD

**Issue by Danny1994d** [JimmyLaurent/cloudflare-scraper#1]
Hello sir, how can use your script to bypass new uam challenge?
here is my exemple code, using cloudscraper
```js
const url= process.argv[2];
function send_req() {
  let proxy = proxies[Math.floor(Math.random() * proxies.length)];
  proxy = new HttpsProxyAgent('http://' + proxy);

  return new Promise((resolve, reject) => {
    cloudscraper.get(url, {
      cloudflareRetry: 10
    }) 
      .then(response => {
        resolve(response);
      })
      .catch(error => {
      return reject(error);
        let obj_v = proxies.indexOf(proxy);
        proxies.splice(obj_v, 1);
      });
  });
}

setInterval(() => {
    send_req();
});```

**Comment by JimmyLaurent** [comment]
This package is in experimental stage, don't expect any captcha bypass or resolution.
Still, here is an example of usage:
```js
const cloudfareScraper = require("cloudflare-scraper");

(async () => {
    try {
        const response = await cloudfareScraper.get("https://audiograb.net");
        console.log(response);
    } catch (error) {
        console.log(error);
    }
})();
```

**Comment by Danny1994d** [comment]
> This package is in experimental stage, don't expect any captcha bypass or resolution.
> Still, here is an example of usage:
> 
> ```js
> const cloudfareScraper = require("cloudflare-scraper");
> 
> (async () => {
>     try {
>         const response = await cloudfareScraper.get("https://audiograb.net");
>         console.log(response);
>     } catch (error) {
>         console.log(error);
>     }
> })();
> ```

I did some tests, the problem is that it takes up to 3 minutes to get the cookie and bypass it

**Comment by JimmyLaurent** [comment]
Maybe it is something with your IP (ex: you flooded cloudflare before) or maybe it is your CPU.
I couldn't reproduce.
<img width="713" alt="Screenshot 2020-06-07 at 09 09 29" src="https://user-images.githubusercontent.com/25406553/83962692-d0870f00-a89f-11ea-90fb-64e3e672d2af.png">

**Comment by Cosmysd** [comment]
@JimmyLaurent  your script working, but calling puppeteer on linux  your script just spamming and get memory leak (opened many chronium)
