### ISSUE TITLE
It's possible to edit User Agent ?

### ISSUE THREAD

**Issue by MathieuGery** [JimmyLaurent/cloudflare-scraper#26]
It's possible to edit User Agent ?

**Comment by RamBoFe** [comment]
For now, you can edit User Agent in _utils.js_ file from line 1 to 6 :

```javascript
const USER_AGENT_MAC =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36';
const USER_AGENT_WINDOWS =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36';
const USER_AGENT_LINUX =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36';
```

This should probably be made configurable in the future.

**Comment by RamBoFe** [comment]
I bring a precision to my previous message. Another way to set up your own User Agent is to use this code found [here](https://github.com/JimmyLaurent/cloudflare-scraper/issues/10#issuecomment-644252960).

This approach avoids touching the source code of the package and is more configurable.

**Comment by MathieuGery** [comment]
Nice this sounds really good I will try !
