### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by ElijahDD** [JimmyLaurent/cloudflare-scraper#5]
How can i get cookies after successful bypass?

**Comment by JimmyLaurent** [comment]
```js
const cloudflareScraper = require('cloudflare-scraper');

(async () => {
 try { 
    const jar = cloudflareScraper.jar();
    const url = 'https://your-url.com'; 
    const response = await cloudflareScraper.get(url, { jar }); 
    const cookiesObject = jar.getCookies(url); const cookieStr = jar.getCookieString(url); 
    console.log(cookieStr); 
} catch (error) {
   console.log(error); 
}
})();
```

**Comment by ElijahDD** [comment]
Thanks

`const response = await cloudflareScraper.get(url, { 
                jar,
                proxy: proxy,
                headers: {
                    'User-Agent': 'something..'
                } 
            }); `

Correct?

**Comment by JimmyLaurent** [comment]
Yes but in some cases cloudflare can detect wrong user agents, so If the bypass is less effective, you'll know why.
And please, no ddos, it's not why I made this tool for.

**Comment by ElijahDD** [comment]
Thank you
I'm interesting not for ddos (headless using CPU too much even in 1 thread, with big amount of proxies server just lag)
